# configuracoes do banco de dados
DATABASE = 'db'
DATABASE_USERNAME = 'fellip'
DATABASE_PASSWORD = 'fellip'
DATABASE_HOST = 'localhost'
DATABASE_PORT = 5432

# configuracao do SQLAlchemy
SQLALCHEMY_DATABASE_URI = f'postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE}'